title: "Klindt Lab - NeuroAI Research"
description: "Exploring the intersection of neuroscience and artificial intelligence"
baseurl: "/website"
url: "https://klindtlab.github.io"
repository: "klindtlab/website"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  team:
    output: true
    permalink: /:collection/:name/
  publications:
    output: true
    permalink: /:collection/:name/
  news:
    output: true
    permalink: /:collection/:year/:month/:day/:title/

# Navigation
header_pages:
  - index.md
  - about.md
  - research.md
  - team.md
  - publications.md
  - news.md

# Social links
github_username: klindtlab
# twitter_username: # Lab doesn't have Twitter yet
email: klindt@cshl.edu

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X